// src/components/react/CookieConsent.tsx
import { useState, useEffect, useCallback } from 'react';
import '@/styles/cookie-consent.css';

type CookieCategory = 'necessary' | 'analytics';

type CookiePreferences = {
  necessary: boolean;
  analytics: boolean;
};

type CookieConsentData = CookiePreferences & {
  date: string;
  version: string;
};

interface CookieConsentProps {
  defaultPreferences?: Partial<CookiePreferences>;
  consentVersion?: string;
}

export default function CookieConsent({
  defaultPreferences,
  consentVersion = '1.0',
}: Readonly<CookieConsentProps>) {
  const [showBanner, setShowBanner] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  const [preferences, setPreferences] = useState<CookiePreferences>({
    necessary: true,
    analytics: defaultPreferences?.analytics ?? false,
  });

  const loadAnalytics = useCallback(() => {
    const script = document.createElement('script');
    script.src = '/_vercel/insights/script.js';
    script.async = true;
    script.dataset.consent = 'analytics';
    document.head.appendChild(script);
  }, []);

  const isScriptLoaded = useCallback((type: string): boolean => {
    return !!document.querySelector(`script[data-consent="${type}"]`);
  }, []);

  const cleanupExpiredConsent = useCallback(() => {
    localStorage.removeItem('cookie-consent');
    localStorage.removeItem('cookie-consent-date');
    localStorage.removeItem('cookie-consent-version');
  }, []);

  const savePreferences = useCallback(
    (prefs: CookiePreferences) => {
      const consentData: CookieConsentData = {
        ...prefs,
        date: new Date().toISOString(),
        version: consentVersion,
      };

      localStorage.setItem('cookie-consent', JSON.stringify(prefs));
      localStorage.setItem('cookie-consent-date', consentData.date);
      localStorage.setItem('cookie-consent-version', consentData.version);

      globalThis.dispatchEvent(
        new CustomEvent('cookieConsentUpdated', { detail: consentData })
      );

      if (prefs.analytics && globalThis.window !== undefined) {
        if (typeof (globalThis as any).loadGTMIfConsented === 'function') {
          (globalThis as any).loadGTMIfConsented();
        }
        if (!isScriptLoaded('analytics')) {
          loadAnalytics();
        }
      }

      setShowBanner(false);
      setShowSettings(false);
    },
    [consentVersion, isScriptLoaded, loadAnalytics]
  );

  const acceptAll = useCallback(() => {
    savePreferences({ necessary: true, analytics: true });
  }, [savePreferences]);

  const acceptNecessary = useCallback(() => {
    savePreferences({ necessary: true, analytics: false });
  }, [savePreferences]);

  const saveCustomPreferences = useCallback(() => {
    savePreferences(preferences);
  }, [savePreferences, preferences]);

  const togglePreference = useCallback((key: CookieCategory) => {
    if (key === 'necessary') return;
    setPreferences((prev) => ({ ...prev, [key]: !prev[key] }));
  }, []);

  useEffect(() => {
    const showBannerFromOutside = () => {
      setShowBanner(true);
      setShowSettings(false);
    };

    (globalThis as any).showCookieBanner = showBannerFromOutside;

    const showBannerHandler = () => {
      setShowBanner(true);
      setShowSettings(false);
    };
    globalThis.addEventListener('showCookieBanner', showBannerHandler);

    const consentStr = localStorage.getItem('cookie-consent');
    const consentDateStr = localStorage.getItem('cookie-consent-date');
    const consentVersionStr = localStorage.getItem('cookie-consent-version');

    if (!consentStr || !consentDateStr) {
      setShowBanner(true);
      return;
    }

    const consentDate = new Date(consentDateStr);
    const thirteenMonthsAgo = new Date();
    thirteenMonthsAgo.setMonth(thirteenMonthsAgo.getMonth() - 13);

    const needsNewConsent =
      consentDate < thirteenMonthsAgo || consentVersionStr !== consentVersion;

    if (needsNewConsent) {
      setShowBanner(true);
      cleanupExpiredConsent();
      return;
    }

    try {
      const consent: CookiePreferences = JSON.parse(consentStr);
      setPreferences((prev) => ({ ...prev, ...consent }));

      if (consent.analytics) {
        loadAnalytics();
      }
    } catch (e) {
      console.error('Erreur lors du chargement des préférences:', e);
      setShowBanner(true);
    }

    return () => {
      globalThis.removeEventListener('showCookieBanner', showBannerHandler);
      delete (globalThis as any).showCookieBanner;
    };
  }, [consentVersion, cleanupExpiredConsent, loadAnalytics]);

  if (!showBanner) return null;

  return (
    <dialog aria-labelledby="cookie-title" open>
      <div className="cookie-banner-content">
        {showSettings ? (
          <div>
            <div className="cookie-settings-header">
              <h3>Préférences des cookies</h3>
              <button
                onClick={() => setShowSettings(false)}
                className="cookie-close"
                aria-label="Retour"
              >
                <svg
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  aria-hidden="true"
                >
                  <line
                    x1="18"
                    y1="6"
                    x2="6"
                    y2="18"
                    strokeWidth="2"
                    strokeLinecap="round"
                  />
                  <line
                    x1="6"
                    y1="6"
                    x2="18"
                    y2="18"
                    strokeWidth="2"
                    strokeLinecap="round"
                  />
                </svg>
              </button>
            </div>

            <div className="cookie-preferences">
              <div className="cookie-pref-item">
                <div className="cookie-pref-text">
                  <p className="cookie-pref-title">Cookies nécessaires</p>
                  <p className="cookie-pref-desc">
                    Requis pour le fonctionnement du site (toujours activés)
                  </p>
                </div>
                <div className="cookie-toggle cookie-toggle-active">
                  <div className="cookie-toggle-thumb"></div>
                </div>
              </div>

              <div className="cookie-pref-item">
                <div className="cookie-pref-text">
                  <p className="cookie-pref-title">Cookies analytiques</p>
                  <p className="cookie-pref-desc">
                    Nous aident à comprendre comment vous utilisez le site
                  </p>
                </div>
                <button
                  onClick={() => togglePreference('analytics')}
                  className={`cookie-toggle ${preferences.analytics ? 'cookie-toggle-active' : ''}`}
                  role="switch"
                  aria-checked={preferences.analytics}
                  aria-label="Activer les cookies analytiques"
                >
                  <div className="cookie-toggle-thumb"></div>
                </button>
              </div>
            </div>

            <div className="cookie-actions">
              <button
                onClick={() => setShowSettings(false)}
                className="cookie-btn cookie-btn-secondary"
              >
                Annuler
              </button>
              <button
                onClick={saveCustomPreferences}
                className="cookie-btn cookie-btn-primary"
              >
                Enregistrer
              </button>
            </div>
          </div>
        ) : (
          <div>
            <div className="cookie-header">
              <div className="cookie-text">
                <h3 id="cookie-banner-title">🍪 Cookies</h3>
                <p id="cookie-banner-description">
                  Nous utilisons des cookies pour améliorer votre expérience. Les
                  cookies nécessaires sont requis pour le fonctionnement du site.
                  Vous pouvez personnaliser vos préférences à tout moment.{' '}
                  <a
                    href="/legal/cookies"
                    style={{ color: 'inherit', textDecoration: 'underline' }}
                  >
                    En savoir plus
                  </a>
                </p>
                <span className="cookie-example">
                  Exemple: session, sécurité, préférences
                </span>
              </div>
              <button
                onClick={acceptNecessary}
                className="cookie-close"
                aria-label="Refuser les cookies optionnels"
              >
                <svg
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  aria-hidden="true"
                >
                  <line
                    x1="18"
                    y1="6"
                    x2="6"
                    y2="18"
                    strokeWidth="2"
                    strokeLinecap="round"
                  />
                  <line
                    x1="6"
                    y1="6"
                    x2="18"
                    y2="18"
                    strokeWidth="2"
                    strokeLinecap="round"
                  />
                </svg>
              </button>
            </div>

            <div className="cookie-actions">
              <button
                onClick={() => setShowSettings(true)}
                className="cookie-btn cookie-btn-secondary"
              >
                <svg
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  aria-hidden="true"
                >
                  <circle cx="12" cy="12" r="3" strokeWidth="2" />
                  <path
                    d="M12 1v6m0 6v6M23 12h-6m-6 0H1"
                    strokeWidth="2"
                    strokeLinecap="round"
                  />
                </svg>
                Personnaliser
              </button>
              <button
                onClick={acceptNecessary}
                className="cookie-btn cookie-btn-secondary"
              >
                Refuser
              </button>
              <button
                onClick={acceptAll}
                className="cookie-btn cookie-btn-primary"
              >
                Accepter tout
              </button>
            </div>
          </div>
        )}
      </div>
    </dialog>
  );
}

// src/components/svelte/CookieConsent.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';

  type CookieCategory = 'necessary' | 'analytics';

  type CookiePreferences = {
    necessary: boolean;
    analytics: boolean;
  };

  type CookieConsentData = CookiePreferences & {
    date: string;
    version: string;
  };

  export let defaultPreferences: Partial<CookiePreferences> | undefined = undefined;
  export let consentVersion: string = '1.0';

  let showBanner = false;
  let showSettings = false;
  let preferences: CookiePreferences = {
    necessary: true,
    analytics: defaultPreferences?.analytics ?? false,
  };

  // Exposer une fonction globale pour montrer le banner (pour le bouton "Gérer mes cookies")
  const showBannerFromOutside = () => {
    showBanner = true;
    showSettings = false;
  };

  onMount(() => {
    // Ajouter la fonction globale
    (window as any).showCookieBanner = showBannerFromOutside;

    // Écouter l'événement pour montrer le banner
    const showBannerHandler = () => {
      showBanner = true;
      showSettings = false;
    };
    window.addEventListener('showCookieBanner', showBannerHandler);

    const consentStr        = localStorage.getItem('cookie-consent');
    const consentDateStr    = localStorage.getItem('cookie-consent-date');
    const consentVersionStr = localStorage.getItem('cookie-consent-version');

    if (!consentStr || !consentDateStr) {
      showBanner = true;
      return;
    }

    const consentDate       = new Date(consentDateStr);
    const thirteenMonthsAgo = new Date();
    thirteenMonthsAgo.setMonth(thirteenMonthsAgo.getMonth() - 13);

    const needsNewConsent = consentDate < thirteenMonthsAgo || consentVersionStr !== consentVersion;

    if (needsNewConsent) {
      showBanner = true;
      cleanupExpiredConsent();
      return;
    }

    try {
      const consent: CookiePreferences = JSON.parse(consentStr);
      preferences = { ...preferences, ...consent };

      if (consent.analytics) {
        loadAnalytics();
      }
    } catch (e) {
      console.error('Erreur lors du chargement des préférences:', e);
      showBanner = true;
    }

    // Cleanup listener
    return () => {
      window.removeEventListener('showCookieBanner', showBannerHandler);
      delete (window as any).showCookieBanner;
    };
  });

  const cleanupExpiredConsent = () => {
    localStorage.removeItem('cookie-consent');
    localStorage.removeItem('cookie-consent-date');
    localStorage.removeItem('cookie-consent-version');

    preferences = {
      necessary: true,
      analytics: false,
    };
  };

  const loadAnalytics = () => {
    const script = document.createElement('script');
    script.src   = '/_vercel/insights/script.js';
    script.async = true;
    script.setAttribute('data-consent', 'analytics');
    document.head.appendChild(script);
  };

  const acceptAll = () => {
    savePreferences({ necessary: true, analytics: true });
  };

  const acceptNecessary = () => {
    savePreferences({ necessary: true, analytics: false });
  };

  const saveCustomPreferences = () => {
    savePreferences(preferences);
  };

  const savePreferences = (prefs: CookiePreferences) => {
    const consentData: CookieConsentData = {
      ...prefs,
      date:    new Date().toISOString(),
      version: consentVersion,
    };

    localStorage.setItem('cookie-consent',         JSON.stringify(prefs));
    localStorage.setItem('cookie-consent-date',    consentData.date);
    localStorage.setItem('cookie-consent-version', consentData.version);

    window.dispatchEvent(
      new CustomEvent('cookieConsentUpdated', { detail: consentData })
    );

    // Charger GTM si analytics accepté et pas déjà chargé
    if (prefs.analytics && typeof window !== 'undefined') {
      if (typeof window.loadGTMIfConsented === 'function') {
        window.loadGTMIfConsented();
      }
      if (!isScriptLoaded('analytics')) {
        loadAnalytics();
      }
    }

    showBanner    = false;
    showSettings  = false;
  };

  const isScriptLoaded = (type: string): boolean => {
    return !!document.querySelector(`script[data-consent="${type}"]`);
  };

  const togglePreference = (key: CookieCategory) => {
    if (key === 'necessary') return;
    preferences = { ...preferences, [key]: !preferences[key] };
  };
</script>

{#if showBanner}
  <div
    class="cookie-banner"
    role="dialog"
    aria-labelledby="cookie-banner-title"
    aria-describedby="cookie-banner-description"
  >
    <div class="cookie-banner-content">
      {#if !showSettings}
        <div>
          <div class="cookie-header">
            <div class="cookie-text">
              <h3 id="cookie-banner-title">🍪 Cookies</h3>
              <p id="cookie-banner-description">
                Nous utilisons des cookies pour améliorer votre expérience. Les cookies nécessaires sont requis pour le fonctionnement du site. Vous pouvez personnaliser vos préférences à tout moment.
                <a href="/legal/cookies" style="color: inherit; text-decoration: underline;">En savoir plus</a>
              </p>
            </div>
            <button
              on:click={acceptNecessary}
              class="cookie-close"
              aria-label="Refuser les cookies optionnels"
            >
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true">
                <line x1="18" y1="6" x2="6" y2="18" stroke-width="2" stroke-linecap="round"/>
                <line x1="6" y1="6" x2="18" y2="18" stroke-width="2" stroke-linecap="round"/>
              </svg>
            </button>
          </div>

          <div class="cookie-actions">
            <button on:click={() => showSettings = true} class="cookie-btn cookie-btn-secondary">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true">
                <circle cx="12" cy="12" r="3" stroke-width="2"/>
                <path d="M12 1v6m0 6v6M23 12h-6m-6 0H1" stroke-width="2" stroke-linecap="round"/>
              </svg>
              Personnaliser
            </button>
            <button on:click={acceptNecessary} class="cookie-btn cookie-btn-secondary">
              Refuser
            </button>
            <button on:click={acceptAll} class="cookie-btn cookie-btn-primary">
              Accepter tout
            </button>
          </div>
        </div>
      {:else}
        <div>
          <div class="cookie-settings-header">
            <h3>Préférences des cookies</h3>
            <button
              on:click={() => showSettings = false}
              class="cookie-close"
              aria-label="Retour"
            >
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true">
                <line x1="18" y1="6" x2="6" y2="18" stroke-width="2" stroke-linecap="round"/>
                <line x1="6" y1="6" x2="18" y2="18" stroke-width="2" stroke-linecap="round"/>
              </svg>
            </button>
          </div>

          <div class="cookie-preferences">
            <div class="cookie-pref-item">
              <div class="cookie-pref-text">
                <p class="cookie-pref-title">Cookies nécessaires</p>
                <p class="cookie-pref-desc">Requis pour le fonctionnement du site (toujours activés)</p>
              </div>
              <div class="cookie-toggle cookie-toggle-active">
                <div class="cookie-toggle-thumb"></div>
              </div>
            </div>

            <div class="cookie-pref-item">
              <div class="cookie-pref-text">
                <p class="cookie-pref-title">Cookies analytiques</p>
                <p class="cookie-pref-desc">Nous aident à comprendre comment vous utilisez le site</p>
              </div>
              <button
                on:click={() => togglePreference('analytics')}
                class="cookie-toggle {preferences.analytics ? 'cookie-toggle-active' : ''}"
                role="switch"
                aria-checked={preferences.analytics}
                aria-label="Activer les cookies analytiques"
              >
                <div class="cookie-toggle-thumb"></div>
              </button>
            </div>
          </div>

          <div class="cookie-actions">
            <button on:click={() => showSettings = false} class="cookie-btn cookie-btn-secondary">
              Annuler
            </button>
            <button on:click={saveCustomPreferences} class="cookie-btn cookie-btn-primary">
              Enregistrer
            </button>
          </div>
        </div>
      {/if}
    </div>
  </div>
{/if}

<style scoped>
  .cookie-banner {
    position: fixed;
    bottom: 24px;
    left: 50%;
    transform: translateX(-50%);
    width: calc(100% - 48px);
    max-width: 520px;
    background: var(--color-bg-elevated);
    border: var(--brutal-border);
    box-shadow: var(--shadow-xl);
    z-index: 10000;
    padding: 28px;
    animation: slideUp 0.4s cubic-bezier(0.16, 1, 0.3, 1);
  }

  @keyframes slideUp {
    from { opacity: 0; transform: translateX(-50%) translateY(30px); }
    to   { opacity: 1; transform: translateX(-50%) translateY(0); }
  }

  .cookie-banner-content {
    display: flex;
    flex-direction: column;
    gap: var(--spacing-lg);
  }

  .cookie-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: var(--spacing-lg);
  }

  .cookie-text h3 {
    margin: 0 0 var(--spacing-sm) 0;
    font-size: var(--font-size-xl);
    font-weight: var(--font-weight-extrabold);
    color: var(--color-text);
    letter-spacing: -0.02em;
    text-transform: uppercase;
  }

  .cookie-text p {
    margin: 0 0 15px 0;
    font-size: var(--font-size-sm);
    color: var(--color-gray-100);
    line-height: 1.6;
    font-weight: var(--font-weight-medium);
  }

  .cookie-close {
    background: var(--color-bg);
    border: var(--brutal-border-thin);
    cursor: pointer;
    padding: 8px;
    display: flex;
    align-items: center;
    justify-content: center;
    color: var(--color-text);
    box-shadow: var(--shadow-sm);
    transition: transform var(--transition-fast), box-shadow var(--transition-fast), background-color var(--transition-fast);
    flex-shrink: 0;
  }

  .cookie-close:hover {
    transform: translate(var(--brutal-hover-lift), var(--brutal-hover-lift));
    box-shadow: var(--shadow-md);
    background: var(--color-primary-light);
  }

  .cookie-close:active {
    transform: translate(var(--brutal-press-translate), var(--brutal-press-translate));
    box-shadow: var(--shadow-press);
  }

  .cookie-close svg {
    width: 20px;
    height: 20px;
    color: var(--color-text);
  }

  .cookie-actions {
    display: flex;
    gap: var(--spacing-sm);
    flex-wrap: wrap;
  }

  .cookie-btn {
    padding: 12px 20px;
    border: var(--brutal-border);
    cursor: pointer;
    font-size: var(--font-size-sm);
    font-weight: var(--font-weight-extrabold);
    transition: transform var(--transition-fast), box-shadow var(--transition-fast), background-color var(--transition-fast);
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
    flex: 1;
    min-width: 140px;
    letter-spacing: 0.5px;
    text-transform: uppercase;
    box-shadow: var(--shadow-lg);
  }

  .cookie-btn svg { width: 18px; height: 18px; }

  .cookie-btn:hover {
    transform: translate(var(--brutal-hover-lift), var(--brutal-hover-lift));
    box-shadow: var(--shadow-glow-hover);
  }

  .cookie-btn:active {
    transform: translate(var(--brutal-press-translate), var(--brutal-press-translate));
    box-shadow: var(--shadow-press);
  }

  .cookie-btn-primary {
    background: var(--color-primary);
    color: var(--color-text);
    border-color: var(--color-border);
  }

  .cookie-btn-primary:hover { background: var(--color-primary-dark); }

  .cookie-btn-secondary {
    background: var(--color-secondary);
    font-size: 13px;
    color: var(--color-text);
    border-color: var(--color-border);
  }

  .cookie-settings-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: var(--spacing-lg);
    padding-bottom: var(--spacing-md);
    border-bottom: var(--brutal-border-thin);
  }

  .cookie-settings-header h3 {
    margin: 0;
    font-size: var(--font-size-lg);
    font-weight: var(--font-weight-extrabold);
    color: var(--color-text);
    letter-spacing: -0.02em;
    text-transform: uppercase;
  }

  .cookie-preferences {
    display: flex;
    flex-direction: column;
    gap: var(--spacing-md);
    margin-bottom: var(--spacing-lg);
  }

  .cookie-pref-item {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: var(--spacing-lg);
    padding: var(--spacing-md);
    background: var(--color-bg);
    border: var(--brutal-border-thin);
    box-shadow: var(--shadow-md);
    transition: transform var(--transition-fast), box-shadow var(--transition-fast);
  }

  .cookie-pref-item:hover {
    transform: translate(-2px, -2px);
    box-shadow: var(--shadow-lg);
  }

  .cookie-pref-text { flex: 1; }

  .cookie-pref-title {
    margin: 0 0 4px 0;
    font-size: var(--font-size-sm);
    font-weight: var(--font-weight-bold);
    color: var(--color-text);
    letter-spacing: -0.01em;
  }

  .cookie-pref-desc {
    margin: 0;
    font-size: var(--font-size-xs);
    color: var(--color-text-light);
    line-height: 1.5;
    font-weight: var(--font-weight-normal);
  }

  .cookie-toggle {
    width: 50px;
    height: 28px;
    background: var(--color-gray-400);
    position: relative;
    transition: background-color var(--transition-base), box-shadow var(--transition-base);
    border: var(--brutal-border-thin);
    cursor: pointer;
    flex-shrink: 0;
    box-shadow: var(--shadow-sm);
  }

  .cookie-toggle:hover {
    transform: translate(-2px, -2px);
    box-shadow: var(--shadow-md);
  }

  .cookie-toggle:active {
    transform: translate(2px, 2px);
    box-shadow: none;
  }

  .cookie-toggle-active {
    background: var(--color-primary);
    box-shadow: var(--shadow-glow);
  }

  .cookie-toggle-thumb {
    width: 18px;
    height: 18px;
    background: var(--color-bg-elevated);
    border: 2px solid var(--color-border);
    position: absolute;
    top: 3px;
    left: 3px;
    transition: transform var(--transition-base), background-color var(--transition-base);
  }

  .cookie-toggle-active .cookie-toggle-thumb {
    transform: translateX(22px);
    background: var(--color-text);
  }

  @media (max-width: 640px) {
    .cookie-banner {
      bottom: 16px;
      width: calc(100% - 32px);
      padding: 24px;
    }

    .cookie-text h3 { font-size: var(--font-size-lg); }
    .cookie-text p  { font-size: var(--font-size-sm); }

    .cookie-actions { flex-direction: column; }
    .cookie-btn     { width: 100%; min-width: unset; }
    .cookie-pref-item { padding: 12px; }
  }
</style>
